version: "3"

services:

  easy_label:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - /static/:/static/
      - /media/:/media/
    container_name: easy_label

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "1337:80"
    volumes:
      - /static/:/static/
      - /media/:/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - easy_label


